# Development environment overrides for lapras landscape
landscape: 'lapras'

clients:
  alcohol:
    zinc:
      url: http://localhost:9003
app:
  name: Alcohol Lapras
  url: http://localhost:3000
  servicetree:
    landscape: 'lapras'
