# Development environment overrides for lapras landscape
landscape: 'lapras'
clients:
  alcohol:
    zinc:
      url: http://localhost:9003
#      url: 'https://api.zinc.alcohol.pichu.cluster.atomi.cloud'
app:
  servicetree:
    landscape: 'lapras'
