# Staging environment overrides for pichu landscape
landscape: 'pichu'

clients:
  alcohol:
    zinc:
      url: 'https://api.zinc.alcohol.pichu.cluster.atomi.cloud'
app:
  servicetree:
    landscape: 'pichu'
