# Staging environment overrides for pichu landscape
landscape: 'pichu'

clients:
  alcohol:
    zinc:
      url: 'https://api.zinc.alcohol.pichu.cluster.atomi.cloud'
app:
  name: Alcohol Pichu
  url: 'https://argon-alcohol-pichu.kirinnee.workers.dev'
  servicetree:
    landscape: 'pichu'
onboarding:
  defaultCharityId: 'c5489b5d-9fbf-493d-b9be-153ad59c96d9'
