# Pre-production environment overrides for pikachu landscape
landscape: 'pikachu'

clients:
  alcohol:
    zinc:
      url: 'https://api.zinc.alcohol.pikachu.cluster.atomi.cloud'
app:
  servicetree:
    landscape: 'pikachu'
