# Pre-production environment overrides for pikachu landscape
landscape: 'pikachu'

clients:
  alcohol:
    zinc:
      url: 'https://api.zinc.alcohol.pikachu.cluster.atomi.cloud'
app:
  name: Alcohol Pikachu
  url: 'https://argon-alcohol-pikachu.kirinnee.workers.dev'
  servicetree:
    landscape: 'pikachu'
onboarding:
  defaultCharityId: '3ba83a10-131f-4182-b9d9-8f12478172da'
