# Production environment overrides for raichu landscape
landscape: 'raichu'

clients:
  alcohol:
    zinc:
      url: 'https://api.zinc.alcohol.raichu.cluster.atomi.cloud'
app:
  name: LazyTax
  url: 'https://lazytax.club'
  servicetree:
    landscape: 'raichu'
onboarding:
  defaultCharityId: 'b2d6cfa3-a114-403e-ae59-64fa54475c44'
