# Base configuration for common settings shared between client and server
app:
  name: 'Alcohol Argon'
  version: '1.0.0'

features:
  debug: false

errorPortal:
  baseUri: 'https://api.zinc.sulfone.pichu.cluster.atomi.cloud'
  version: '1.0'
  service: 'argon'
