# Base configuration for common settings shared between client and server

app:
  name: 'LazyTax'
  build:
    sha: 'unknown'
    version: 'unknown'
    time: 0
  servicetree:
    landscape: 'unknown'
    platform: 'alcohol'
    service: 'argon'
    module: 'webapp'

errorPortal:
  baseUri: 'https://api.zinc.sulfone.pichu.cluster.atomi.cloud'
  version: '1.0'
  service: 'argon'

clients:
  alcohol:
    zinc:
      url: 'http://localhost:9003'
