# Base configuration for common settings shared between client and server

app:
  name: 'Alcohol Argon'
  version: '1.0.0'
  build:
    sha: 'unknown'
    version: 'unknown'
    time: 0
  servicetree:
    landscape: 'unknown'
    platform: 'alcohol'
    service: 'argon'
    module: 'webapp'

features:
  debug: false

errorPortal:
  baseUri: 'https://api.zinc.sulfone.pichu.cluster.atomi.cloud'
  version: '1.0'
  service: 'argon'
