version: '3'

tasks:
  build:
    desc: 'Build the application with OpenNext'
    cmds:
      - eval "$(./scripts/ci/export_build_info.sh)" && bunx opennextjs-cloudflare build

  lint:
    desc: 'Lint the repository'
    cmds:
      - pre-commit run --all-files

  dev:
    desc: 'Start development server with live-reload'
    summary: |
      Builds the app with OpenNext and starts wrangler dev with live-reload.
      This provides the best development experience matching production runtime.
    cmds:
      - bunx next dev

  preview:
    desc: 'Preview the application'
    summary: |
      Same as dev - builds with OpenNext and starts wrangler dev.
    env:
      LANDSCAPE: lapras
    cmds:
      - ./scripts/local/preview.sh

  upload:
    desc: 'Upload to specific landscape'
    summary: |
      Upload to a specific landscape environment.

      Usage: pls upload <landscape>

      Landscapes: lapras, pichu, pikachu, raichu
      Tag: Optional release tag to include in description
    cmds:
      - ./scripts/ci/upload.sh {{.CLI_ARGS}} upload "local-$(openssl rand -hex 3)"
  deploy:
    desc: 'Deploy to specific landscape'
    summary: |
      Deploy to a specific landscape environment.

      Usage: pls deploy <landscape>

      Landscapes: lapras, pichu, pikachu, raichu
      Tag: Optional release tag to include in description
    cmds:
      - ./scripts/ci/upload.sh {{.CLI_ARGS}} deploy "local-$(openssl rand -hex 3)"

  generate:sdk:
    desc: 'Generate SDK clients from OpenAPI specifications'
    summary: |
      Generate TypeScript SDK clients for all configured services.
      Uses swagger-typescript-api to create type-safe API clients.
    cmds:
      - task: generate:sdk:zinc

  generate:sdk:zinc:
    desc: 'Generate Zinc service SDK'
    summary: |
      Generate TypeScript SDK client for the Zinc service.

      Usage: task generate:sdk:zinc [SPEC_URL]
    cmds:
      - ./scripts/local/generate-sdk.sh zinc {{.SPEC_URL | default "https://api.zinc.alcohol.pichu.cluster.atomi.cloud/swagger/v1/swagger.json"}}
