version: '3'

tasks:
  setup:
    desc: 'Setup the repository'
    cmds:
      - bun install

      - ./scripts/local/secrets.sh
  lint:
    desc: 'Lint the repository'
    cmds:
      - pre-commit run --all-files
