name = "alcohol-argon-frontend"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"

# Enable Node.js API compatibility
# See: https://developers.cloudflare.com/workers/configuration/compatibility-flags/#nodejs-compatibility-flag
# Allow to fetch URLs in your app
# See: https://developers.cloudflare.com/workers/configuration/compatibility-flags/#global-fetch-strictly-public
compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public"
]

# Static assets configuration
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1 

# R2 bucket configuration for incremental caching
# Uncomment and configure when setting up R2 for enhanced caching
# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "<BUCKET_NAME>"

# Environment-specific configurations
[env.lapras]
name = "argon-alcohol-lapras"
vars = { NEXTJS_ENV = "development", LANDSCAPE = "lapras" }

[env.pichu]
name = "argon-alcohol-pichu"
vars = { NEXTJS_ENV = "production", LANDSCAPE = "pichu" }

[env.pikachu]
name = "argon-alcohol-pikachu"
vars = { NEXTJS_ENV = "production", LANDSCAPE = "pikachu" }

[env.raichu]
name = "argon-alcohol-raichu"
vars = { NEXTJS_ENV = "production", LANDSCAPE = "raichu" } 