name = "alcohol-argon-frontend"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"

# Enable Node.js API compatibility
# See: https://developers.cloudflare.com/workers/configuration/compatibility-flags/#nodejs-compatibility-flag
# Allow to fetch URLs in your app
# See: https://developers.cloudflare.com/workers/configuration/compatibility-flags/#global-fetch-strictly-public
compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public"
]

# Static assets configuration
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Service bindings
[[services]]
binding = "WORKER_SELF_REFERENCE"
# The service should match the "name" of your worker
service = "alcohol-argon-frontend"

# R2 bucket configuration for incremental caching
# Uncomment and configure when setting up R2 for enhanced caching
# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "<BUCKET_NAME>" 