landscape: unknown
db:
  url: none
auth:
  logto:
    app:
      secret: supersecret
      id: id
      endpoint: https://unknown
    url: https://unknown
    cookie:
      secret: supersecret
    scopes:
      - openid
      - profile
      - offline_access
      - email
      - admin
      - active
    resources: {}
