# Base configuration for client-safe settings
tracker:
  plausible:
    enabled: true
    domain: 'lazytax.club'
  fathom:
    enabled: true
    id: BHLERINB
support:
  email: support@local.host
navbarshowoff: false
navbar:
  showAuth: false
faro:
  enabled: false
  collectorurl: ''
  sessionTracking:
    enabled: false
    samplingRate: 0
  build:
    enabled: false
    endpoint: https://faro-api-prod-ap-southeast-1.grafana.net/faro/api/v1
    app: '751'
    stack: '818828'
    key: 'unknown'
    gzipContents: true
