name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  upload:
    name: Upload to Landscapes
    uses: ./.github/workflows/⚡reusable-upload.yaml
    secrets: inherit
    with:
      atomi_platform: alcohol
      atomi_service: argon
      release_tag: ${{ github.ref_name }}
